baseURL = 'http://example.org/' 
languageCode = 'en-us'
theme = "JuiceBar"
title = "Puffer"

[params]
author = "Priyanshu Kumar"
description = "My site description"
authorImage = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT4XR04cgYItp6-9injkz5osegQh9aM_nuXA&usqp=CAU"
paginate = 5 
Title = "Hola!"
content = "I'm Priyanshu, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT4XR04cgYItp6-9injkz5osegQh9aM_nuXA&usqp=CAU"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "Github"
url = "https://github.com/hotjuicew"
[[params.social]]
name = "telegram"
url = "https://t.me/Hotjuice"
[[params.social]]
name = "twitter"
url = "https://twitter.com/hotjuicee"
[[params.social]]
name = "email"
url = "mailto:hotjuicew@outlook.com"
[[params.social]]
name = "instagram"
url = "your_url"
[[params.social]]
name = "mastodon"
url = "your_url"
[[params.social]]
name = "reddit"
url = "your_url"
[[params.social]]
name = "stackoverflow"
url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link

[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post/post1"
[[menu.main]]
name = "Categories"
url = "/categories"

# If using the giscus commenting system
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]